version: '3'
services:
  golang-dev:
    build:
      context: .
    image: tf-dev:0.1
    container_name: tf-dev
    working_dir: /var/app
    volumes:
      - '.:/var/app'
    stdin_open: true
    tty: true
